"""Role-prompt definitions layered on top of ResearchHarness."""

from markscientist.prompts.v01_prompts import (
    EVALUATOR_ROLE_PROMPT,
    IMPROVEMENT_REQUEST_TEMPLATE,
    JUDGE_ROLE_PROMPT,
    META_EVALUATION_TEMPLATE,
    REVIEW_REQUEST_TEMPLATE,
    SOLVER_ROLE_PROMPT,
)

__all__ = [
    "SOLVER_ROLE_PROMPT",
    "JUDGE_ROLE_PROMPT",
    "EVALUATOR_ROLE_PROMPT",
    "REVIEW_REQUEST_TEMPLATE",
    "IMPROVEMENT_REQUEST_TEMPLATE",
    "META_EVALUATION_TEMPLATE",
]
